import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'hi', 'te', 'bn', 'kn', 'mr'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? hiText = '',
    String? teText = '',
    String? bnText = '',
    String? knText = '',
    String? mrText = '',
  }) =>
      [enText, hiText, teText, bnText, knText, mrText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // AuthPage
  {
    'u0030kob': {
      'en': 'Loan.ly kya?',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'fbfpwxvb': {
      'en': 'Create Account',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'oeautvp7': {
      'en': 'Create Account',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'h9ey3qek': {
      'en': 'Start by entering your email and setting a secure password.',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'tjzmb9i3': {
      'en': 'Enter your Email Address',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '589rx3qn': {
      'en': 'Choose a Password',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'xob58dip': {
      'en': 'Confirm your Password',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'qqklkglx': {
      'en': 'Verify Email',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '7b70yxio': {
      'en': 'Log In',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'mpnffyc5': {
      'en': 'Welcome Back',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '5f6wp0as': {
      'en':
          'Sign in to your account to begin browsing eligible loans from 100+ lenders.',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'nteh6u71': {
      'en': 'Email',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'v6et3kj2': {
      'en': 'Password',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'cs8k5wl0': {
      'en': 'Sign In',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'v3upzip6': {
      'en': 'Forgot Password?',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '770pnt6v': {
      'en': 'Home',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // CreateProfilePage
  {
    'y0oe79wq': {
      'en': 'Your Name',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'sh7bcnxj': {
      'en': 'Your Name',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'f8zaunb4': {
      'en': 'Your Mobile Number',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'vmzatwpz': {
      'en': 'Your City',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '39rba9s5': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'epslzhk4': {
      'en': 'Your Gender',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'q7rpj5z4': {
      'en': 'Male',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'm1394nib': {
      'en': 'Female',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'z77ou3zf': {
      'en': 'Non-Binary',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'olxxog5q': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '9bmg0o0l': {
      'en': 'Your Emergency',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'zp8ax5am': {
      'en': 'Medical',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '6onxtckh': {
      'en': 'Educational',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'kvuswz6o': {
      'en': 'Disaster',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'r7hvtdng': {
      'en': 'Personal',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'jckttwow': {
      'en': 'Monthly Income (in rupees)',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'la82clog': {
      'en': 'Save ',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '6idwr56e': {
      'en': 'Create your Profile',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // ForgotPasswordPage
  {
    '9tjzw46h': {
      'en': 'Back',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'kr5vwxa9': {
      'en': 'Forgot Password',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '6d4iwnxz': {
      'en':
          'Enter your registered email address to receive a link to reset your password.',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '6gzmn1vg': {
      'en': 'Your email address...',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'n27cs8c7': {
      'en': 'Enter your email...',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'e1q7rwyz': {
      'en': 'Send Link',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'n3gvdp1w': {
      'en': 'Home',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // OnboardingPage
  {
    '2ut4x55a': {
      'en': 'Welcome to Loan.ly!',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    's846uoxj': {
      'en':
          'Thanks for joining! Access or create your account below, and get started on your journey!',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'c6ab4n10': {
      'en': 'Get Started',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '1q44qhmr': {
      'en': 'Home',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // MainDashboardPage
  {
    've0r0877': {
      'en': 'Loan.ly',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'gjno5fas': {
      'en': 'Find your loan application...',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '9jgy8mob': {
      'en': 'Today\'s Top Three',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'd4nsqj2h': {
      'en': 'Lender',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'e2nosuu2': {
      'en': 'Loan Y',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'wr69k12h': {
      'en': 'Rs. 10,000 - Rs. 30,000',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'p6xc7tir': {
      'en': 'Rating',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'xr43i830': {
      'en': '4.6',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'nq3rzn4y': {
      'en': 'At a Glance',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'cmf7kxaf': {
      'en': 'Due',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'o7r0k6rm': {
      'en': 'Lender',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'rf50mj6s': {
      'en': 'Please conside settling as soon as possible.',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'wwk9x4hd': {
      'en': 'Due',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '8i1dfe4h': {
      'en': 'Past Due',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'oxmiasu6': {
      'en': 'Ongoing',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'z1lak0ho': {
      'en': 'Lender',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'iqrjeg5i': {
      'en': 'Amount has been disbursed. Repay timely.',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'vmjgsxps': {
      'en': 'Due',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'm4umnoq4': {
      'en': 'In Progress',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'mb53vfuh': {
      'en': 'Settled',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'mfmbkpyp': {
      'en': 'Lender',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'uig9mbv0': {
      'en': 'All settled up. Good job!',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '9wfft3ni': {
      'en': 'Completed',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'd9i4k5xn': {
      'en': 'Complete',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'ysuqnmvg': {
      'en': 'Home',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // SupportPage
  {
    'f53pfd4a': {
      'en': 'Hey! How can we help?',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'pdci8fz1': {
      'en': 'Submit a Ticket',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '57b9gt52': {
      'en': 'Call Us',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '92peg96e': {
      'en': 'Email Us',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'wuvb0w4m': {
      'en': 'Search FAQs',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'qogwreaq': {
      'en': 'Channel Name',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'is0pt4id': {
      'en': 'Channel ID',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '64nkbhtk': {
      'en': 'Short Description of what is going on...',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '9vn6jrd5': {
      'en': 'Upload Screenshot',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '8yy75k0e': {
      'en': 'Submit Ticket',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'ir5x9qh6': {
      'en': 'SupportPage',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // NotificationsPage
  {
    'udvkmj38': {
      'en': 'Notification 1',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'ne5pxlfn': {
      'en': '2 hours ago',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'utb9yxno': {
      'en': 'Notification 2',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'hh6zwb1q': {
      'en': '2 hours ago',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'q4dw301d': {
      'en': 'Notification 3',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'ci7zdxbg': {
      'en': '2 hours ago',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'rglbjiqu': {
      'en': 'Notification 4',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'kgcd7610': {
      'en': '2 hours ago',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'x36hd7kq': {
      'en': 'Notifications',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'jugxbfpx': {
      'en': 'Home',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // ProfileSettingsPage
  {
    'nu164en3': {
      'en': 'Namaste!',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'jtvgu8m8': {
      'en': 'Your Account',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'amg3mwnl': {
      'en': 'View Profile',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '783q8y9u': {
      'en': 'Edit Profile',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '763mx2eh': {
      'en': 'Notification Settings',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'efzipjk5': {
      'en': 'App Settings',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '6y39m06w': {
      'en': 'Terms of Service',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'g5iebys2': {
      'en': 'Log Out',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'hje43kbq': {
      'en': 'Profile',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // NotificationSettings
  {
    't15fp1ie': {
      'en': 'Settings Page',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'o1agf5ai': {
      'en':
          'Choose what notifcations you want to recieve below and we will update the settings.',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '6z62yoy5': {
      'en': 'Push Notifications',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    't28sr9ju': {
      'en':
          'Receive Push notifications from our application on a semi regular basis.',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'r5d6yp8p': {
      'en': 'Email Notifications',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'wgisyzz6': {
      'en':
          'Receive email notifications from our marketing team about new features.',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'giclyw94': {
      'en': 'Location Services',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '75dfutn2': {
      'en':
          'Allow us to track your location, this helps keep track of spending and keeps you safe.',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'g7z7qad9': {
      'en': 'Apply Changes',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'twd4lm7r': {
      'en': 'Home',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // TermsOfService
  {
    'yjycs07i': {
      'en': 'Terms of Service',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'r3k4wg0k': {
      'en': 'Home',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // ResetPasswordPage
  {
    '3a9sq6a0': {
      'en': 'Back',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'ad8pih6e': {
      'en': 'Reset Password',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'hch2w0gu': {
      'en': 'Please enter and confirm your new password.',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'zd0uujno': {
      'en': 'Enter new password',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'c3bcvvow': {
      'en': 'Confirm new password',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    's1pztyl3': {
      'en': 'Confirm',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'pmjvglbb': {
      'en': 'Home',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // EditProfilePage
  {
    '321icx6h': {
      'en': 'Enter your Full Name',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'sk9thsm2': {
      'en': 'Enter your Mobile Number',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'mf4aeoyc': {
      'en': 'Enter an Indian city',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'yn9okvnj': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '6jfeme55': {
      'en': 'Select your Gender',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '9ntimi0n': {
      'en': 'Male',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'dydfqkkl': {
      'en': 'Female',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '9th20aco': {
      'en': 'Non-Binary',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    's2ytgxad': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'mvrc7usm': {
      'en': 'Select your Emergency',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'k8ofvyov': {
      'en': 'Medical',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'l4kixvok': {
      'en': 'Educational',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'y00qyi76': {
      'en': 'Disaster',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'xk6beyg4': {
      'en': 'Personal',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'ov1ti2zn': {
      'en': 'Enter your Income (in rupees/month)',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '454apu8f': {
      'en': 'Save Changes',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'vh51ouv4': {
      'en': 'Edit your Profile',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // MainProfilePage
  {
    'd4grp1d8': {
      'en': 'Kshitij Kumar',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'a2nlihr8': {
      'en': 'kshitijkumar2211@gmail.com',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '2sv6tniw': {
      'en': 'My Profile',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'm02mw8aa': {
      'en': 'Mobile Number',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '4gat4xjd': {
      'en': '+91 6364741652',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'xt1cbz6h': {
      'en': 'City',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'pqn904k6': {
      'en': 'Bengaluru',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'mwzi8jo2': {
      'en': 'Income',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'w21bxlij': {
      'en': 'Rs. 10,00,000',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    't06rld9x': {
      'en': 'Gender',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '4eb00let': {
      'en': 'Male',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'zfbvat1w': {
      'en': 'Main Profile',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // CommunityPage
  {
    'pwfqrrju': {
      'en': 'Community Trust Hub',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'lof7p730': {
      'en': 'Your Trust ID Card',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'flomeogo': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '259tl1su': {
      'en': 'Referrals: 3',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'f5vof4zn': {
      'en': 'Validations: 5',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'bsb8mhri': {
      'en': 'Repayment %: 93',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'ov2xt8bg': {
      'en': 'Joined: 01/01/2025',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'w4v4ulys': {
      'en': 'Community Pulse',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'vbtu05ov': {
      'en': 'Number of Members: 89/150',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'cj4l1vlp': {
      'en': 'Active Loans: 17',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'ti4i5fcy': {
      'en': 'Total Risk Pool: Rs. 2,450',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'qzppecw3': {
      'en': 'Giving Score: 55',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'c2l2oxg3': {
      'en': 'Community Members:',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'aqfg812d': {
      'en': 'Member',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'n0qvrcot': {
      'en': 'Member 2',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'njxc51kn': {
      'en': 'Member 3',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'hkylx6b9': {
      'en': 'Member 4',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '5e2lpr12': {
      'en': 'Community',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
  // Miscellaneous
  {
    'uuvtp1cu': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'sasvnj6x': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '9tlaf1x7': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '4oq8mkkv': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'l7kv99zs': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'd5aqj673': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '5qfnyolu': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'd6j516wh': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'snzryb3r': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'f32ssits': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'yk5jlqyl': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'uctvw2sz': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '75adhf5k': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '8art08y1': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'zl21ega7': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '9lq0la1t': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '6co2jfvz': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'yudku29w': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'gmxj3ghh': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'rbreupyf': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '1qjs68f5': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    'y6vkt2hd': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '09lwjujx': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '3pz1l20s': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
    '0cay0dbl': {
      'en': '',
      'bn': '',
      'hi': '',
      'kn': '',
      'mr': '',
      'te': '',
    },
  },
].reduce((a, b) => a..addAll(b));
